### ISSUE TITLE
#1. Journey as a software developer [ pilot meetup ]

### ISSUE THREAD

**Issue by imhta** [remoteship/remote-meetup#1]
## Welcome devs
This is a first weekly remote meetup organized by @remoteship

**Moderators:**  @imhta and @ngodi 

Suggested time is around UTC 14.00 

Interested devs can subscribe to this issue for updates.

**Comment by ngodi** [comment]
Hey Devs register via the form below.
https://forms.gle/BgF6sHuxvDXwxsYc6

**Comment by imhta** [comment]
Time and date are still not decided. so kindly suggest.

**Comment by thsvr** [comment]
On Microverse we have 3 different timezones of work, so I guess Saturday or Sanday people (in general) will be more available.

Suggestion: who agree with it could like this comment, people who don't agree could dislike and you guys can check how many likes and dislikes you got.

**Comment by imhta** [comment]
This is the pilot meetup, even us has little idea 💡 about what gonna happen in this weekend.

But here a list of things you can expect from the meetup.
As moderators, we will explain the agenda.  - 10mins
Then a self-intro between fellow attendees. - each attendee 1 min
Depends upon the number of attendees, we will ask everyone to speak about the journey as a software developer. - each attendee 5 mins (it varies)
Finally, we will share ideas about the future of this developer group. - 5 mins

We will try to wrap everything 1.5 to 2 hrs.

Spoilers
It is difficult to give everyone a chance to speak if we have more attendees. so the plan is to motivate fellow attendees to conduct meetups of their own and this repo will act as a board for events.

**Comment by imhta** [comment]
The plan is the only weekends, not week dates.

What about UTC 14.00?

And SAT or SUN?

**Comment by imhta** [comment]
> On Microverse we have 3 different timezones of work, so I guess Saturday or Sanday people (in general) will be more available.
> 
> Suggestion: who agree with it could like this comment, people who don't agree could dislike and you guys can check how many likes and dislikes you got.

The plan is the only weekends, not week dates.

What about UTC 14.00?

And SAT or SUN?

**Comment by mapra99** [comment]
I'd say 

> > On Microverse we have 3 different timezones of work, so I guess Saturday or Sanday people (in general) will be more available.
> > Suggestion: who agree with it could like this comment, people who don't agree could dislike and you guys can check how many likes and dislikes you got.
> 
> The plan is only weekends, not week dates.
> 
> What about UTC 14.00?
> 
> And SAT or SUN?

I think that SAT is better

**Comment by Redvanisation** [comment]
> The plan is only weekends, not week dates.
> 
> What about UTC 14.00?
> 
> And SAT or SUN?

This is a great idea, but the time is the real challenge here, I suggest if you guys could make it at night time UTC, that way it would be possible for people in other time zones like myself to attend.

**Comment by imhta** [comment]
> > The plan is only weekends, not week dates.
> > What about UTC 14.00?
> > And SAT or SUN?
> 
> This is a great idea, but the time is the real challenge here, I suggest if you guys could make it at night time UTC, that way it would be possible for people in other time zones like myself to attend.

That's true. suggest any time you feel it is right for your time zone.

**Comment by ngodi** [comment]
We have two timezones at microverse; utc-7 and utc, the idea is to suggest
a time that you think may work for both timezones. We proposed 14:00 UTC

**Comment by imhta** [comment]
As for as there is no discussion happening. So we are fixing Day and time of the meetup as

**Sat 14.30 UTC**
I think this match both the timezone

**Comment by imhta** [comment]
Meetup zoom link will be posted in 10 mins

**Comment by imhta** [comment]
https://zoom.us/j/213344487?pwd=NVpSTW03YTJSSmdkcVV0NE9VeWtWdz09

The meetup will start at 14.30 UTC

**Comment by imhta** [comment]
https://zoom.us/j/318543723?pwd=Q1R6djJraGU5R0YzdmFVdE41SnZVUT09
The meetup will start at 14.30 UTC

**Comment by imhta** [comment]
session 2 of the meetup  
https://microverse.zoom.us/j/371844897

**Comment by imhta** [comment]
### We are closing this issue the pilot meetup was over with 4 attendees.
 **we will soon update about upcoming technical meetups.**

any queries contact me in slack under @ponmuthuselvam
