### ISSUE TITLE
#3 Remote meetup on contributing to opensource 

### ISSUE THREAD

**Issue by imhta** [remoteship/remote-meetup#3]
![image](https://user-images.githubusercontent.com/25448577/66820370-2cda9e80-ef5e-11e9-80b8-9fe578213abd.png)

## Welcome devs 👋 

The stencil is a compiler that generates Web Components (more specifically, Custom Elements). Stencil combines the best concepts of the most popular frameworks into a simple build-time tool.

3rd remote meetup from @remoteship

Organizer: @imhta 

**What you can expect**
As moderators, we will explain the agenda. - 10mins
Then a self-intro between fellow attendees. - each attendee 1 min
Let's learn and contribute to an open-source web component project - 1 hr
Finally, we will share ideas about the future of this developers group. - 5 mins

We will try to wrap everything 1.5 hrs.

Anyone can attend but it is good to have a basic idea on TS (Typescript), JS (Javascript)

The meeting link will be posted 10 mins before the meeting start time.

To get a notification 🔔 subscribe to the thread or leave a comment in it.

**Comment by lucaasdfg** [comment]
great !

**Comment by mihrab34** [comment]
Ok, cool

**Comment by rsundar** [comment]
Looking forward to meeting y'all!

**Comment by ir3ne** [comment]
great!

**Comment by rsundar** [comment]
Hey guys @imhta is not available to start the meetup right now, shall we kick it off?

**Comment by rsundar** [comment]
https://zoom.us/j/304953617?pwd=RW1tVyswTzBKQTJFS2M4MEVydnMrZz09

Meeting link

**Comment by abdulmateen-1** [comment]
Great, hope this is still open.

**Comment by imhta** [comment]
Yes, it is still open. Sorry everyone i couldn't organize this meetup because of some personal reasons till now.  Can we do it tommorow On 14.30 UTC ? same time.

If anyone following this still now, give a 👍

**Comment by abdulmateen-1** [comment]
👍🏿

**Comment by rsundar** [comment]
OK

**Comment by imhta** [comment]
Here is the link
https://zoom.us/j/555211755?pwd=UjhkUmlJTVBZTVpsU2RLVjh4YlJnZz09
